/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primitive colors
        'base': {
          'white': 'var(--color-primitive-base-white)',
          'black': 'var(--color-primitive-base-black)',
        },
        'grey': {
          '10': 'var(--color-primitive-grey-10)',
          '20': 'var(--color-primitive-grey-20)',
          '30': 'var(--color-primitive-grey-30)',
          '40': 'var(--color-primitive-grey-40)',
          '50': 'var(--color-primitive-grey-50)',
          '60': 'var(--color-primitive-grey-60)',
          '70': 'var(--color-primitive-grey-70)',
          '80': 'var(--color-primitive-grey-80)',
          '90': 'var(--color-primitive-grey-90)',
          '95': 'var(--color-primitive-grey-95)',
        },
        'sand': {
          '10': 'var(--color-primitive-sand-10)',
          '20': 'var(--color-primitive-sand-20)',
          '30': 'var(--color-primitive-sand-30)',
          '40': 'var(--color-primitive-sand-40)',
          '50': 'var(--color-primitive-sand-50)',
          '60': 'var(--color-primitive-sand-60)',
          '70': 'var(--color-primitive-sand-70)',
          '80': 'var(--color-primitive-sand-80)',
          '90': 'var(--color-primitive-sand-90)',
          '95': 'var(--color-primitive-sand-95)',
        },
        'orange': {
          '10': 'var(--color-primitive-orange-10)',
          '20': 'var(--color-primitive-orange-20)',
          '30': 'var(--color-primitive-orange-30)',
          '40': 'var(--color-primitive-orange-40)',
          '50': 'var(--color-primitive-orange-50)',
          '60': 'var(--color-primitive-orange-60)',
          '70': 'var(--color-primitive-orange-70)',
          '80': 'var(--color-primitive-orange-80)',
          '90': 'var(--color-primitive-orange-90)',
          '95': 'var(--color-primitive-orange-95)',
        },
        'red': {
          '10': 'var(--color-primitive-red-10)',
          '20': 'var(--color-primitive-red-20)',
          '30': 'var(--color-primitive-red-30)',
          '40': 'var(--color-primitive-red-40)',
          '50': 'var(--color-primitive-red-50)',
          '60': 'var(--color-primitive-red-60)',
          '70': 'var(--color-primitive-red-70)',
          '80': 'var(--color-primitive-red-80)',
          '90': 'var(--color-primitive-red-90)',
          '95': 'var(--color-primitive-red-95)',
        },
        'success': {
          '10': 'var(--color-primitive-success-10)',
          '20': 'var(--color-primitive-success-20)',
          '30': 'var(--color-primitive-success-30)',
          '40': 'var(--color-primitive-success-40)',
          '50': 'var(--color-primitive-success-50)',
          '60': 'var(--color-primitive-success-60)',
          '70': 'var(--color-primitive-success-70)',
          '80': 'var(--color-primitive-success-80)',
          '90': 'var(--color-primitive-success-90)',
          '95': 'var(--color-primitive-success-95)',
        },
        'warning': {
          '10': 'var(--color-primitive-warning-10)',
          '20': 'var(--color-primitive-warning-20)',
          '30': 'var(--color-primitive-warning-30)',
          '40': 'var(--color-primitive-warning-40)',
          '50': 'var(--color-primitive-warning-50)',
          '60': 'var(--color-primitive-warning-60)',
          '70': 'var(--color-primitive-warning-70)',
          '80': 'var(--color-primitive-warning-80)',
          '90': 'var(--color-primitive-warning-90)',
          '95': 'var(--color-primitive-warning-95)',
        },
        'error': {
          '10': 'var(--color-primitive-error-10)',
          '20': 'var(--color-primitive-error-20)',
          '30': 'var(--color-primitive-error-30)',
          '40': 'var(--color-primitive-error-40)',
          '50': 'var(--color-primitive-error-50)',
          '60': 'var(--color-primitive-error-60)',
          '70': 'var(--color-primitive-error-70)',
          '80': 'var(--color-primitive-error-80)',
          '90': 'var(--color-primitive-error-90)',
          '95': 'var(--color-primitive-error-95)',
        },
        'info': {
          '10': 'var(--color-primitive-info-10)',
          '20': 'var(--color-primitive-info-20)',
          '30': 'var(--color-primitive-info-30)',
          '40': 'var(--color-primitive-info-40)',
          '50': 'var(--color-primitive-info-50)',
          '60': 'var(--color-primitive-info-60)',
          '70': 'var(--color-primitive-info-70)',
          '80': 'var(--color-primitive-info-80)',
          '90': 'var(--color-primitive-info-90)',
          '95': 'var(--color-primitive-info-95)',
        },
        // Semantic colors
        'content': {
          'primary': 'var(--color-semantic-content-primary)',
          'secondary': 'var(--color-semantic-content-secondary)',
          'tertiary': 'var(--color-semantic-content-tertiary)',
          'disabled': 'var(--color-semantic-content-disabled)',
          'placeholder': 'var(--color-semantic-content-placeholder)',
          'inverse': 'var(--color-semantic-content-inverse)',
          'success': 'var(--color-semantic-content-success)',
          'warning': 'var(--color-semantic-content-warning)',
          'error': 'var(--color-semantic-content-error)',
          'info': 'var(--color-semantic-content-info)',
        },
        'background': {
          'primary': 'var(--color-semantic-background-primary)',
          'secondary': 'var(--color-semantic-background-secondary)',
          'contrast': 'var(--color-semantic-background-contrast)',
          'recessive': 'var(--color-semantic-background-recessive)',
        },
        'surface': {
          'primary': 'var(--color-semantic-surface-primary)',
          'secondary': 'var(--color-semantic-surface-secondary)',
          'recessive': 'var(--color-semantic-surface-recessive)',
          'inverse': 'var(--color-semantic-surface-inverse)',
          'success': 'var(--color-semantic-surface-success)',
          'warning': 'var(--color-semantic-surface-warning)',
          'error': 'var(--color-semantic-surface-error)',
          'info': 'var(--color-semantic-surface-info)',
        },
        'fill': {
          'primary': 'var(--color-semantic-fill-primary)',
          'primary-hover': 'var(--color-semantic-fill-primary-hover)',
          'primary-active': 'var(--color-semantic-fill-primary-active)',
          'secondary': 'var(--color-semantic-fill-secondary)',
          'secondary-hover': 'var(--color-semantic-fill-secondary-hover)',
          'secondary-active': 'var(--color-semantic-fill-secondary-active)',
          'tertiary': 'var(--color-semantic-fill-tertiary)',
          'tertiary-hover': 'var(--color-semantic-fill-tertiary-hover)',
          'tertiary-active': 'var(--color-semantic-fill-tertiary-active)',
          'success': 'var(--color-semantic-fill-success)',
          'warning': 'var(--color-semantic-fill-warning)',
          'error': 'var(--color-semantic-fill-error)',
          'info': 'var(--color-semantic-fill-info)',
          'success-hover': 'var(--color-semantic-fill-success-hover)',
          'success-active': 'var(--color-semantic-fill-success-active)',
          'warning-hover': 'var(--color-semantic-fill-warning-hover)',
          'warning-active': 'var(--color-semantic-fill-warning-active)',
          'error-hover': 'var(--color-semantic-fill-error-hover)',
          'error-active': 'var(--color-semantic-fill-error-active)',
          'info-hover': 'var(--color-semantic-fill-info-hover)',
          'info-active': 'var(--color-semantic-fill-info-active)',
          'secondary-pressed': 'var(--color-semantic-fill-secondary-pressed)',
          'primary-pressed': 'var(--color-semantic-fill-primary-pressed)',
          'tertiary-pressed': 'var(--color-semantic-fill-tertiary-pressed)',
          'success-pressed': 'var(--color-semantic-fill-success-pressed)',
          'warning-pressed': 'var(--color-semantic-fill-warning-pressed)',
          'error-pressed': 'var(--color-semantic-fill-error-pressed)',
          'info-pressed': 'var(--color-semantic-fill-info-pressed)',
          'inactive': 'var(--color-semantic-fill-inactive)',
          'rating-active': 'var(--color-semantic-fill-rating-active)',
          'rating-inactive': 'var(--color-semantic-fill-rating-inactive)',
        },
        'border': {
          'default': 'var(--color-semantic-light-border-default)',
          'active': 'var(--color-semantic-light-border-active)',
          'filled': 'var(--color-semantic-light-border-filled)',
          'success': 'var(--color-semantic-light-border-success)',
          'warning': 'var(--color-semantic-light-border-warning)',
          'error': 'var(--color-semantic-light-border-error)',
          'info': 'var(--color-semantic-light-border-info)',
          'strong': 'var(--color-semantic-light-border-strong)',
          'stronger': 'var(--color-semantic-light-border-stronger)',
          'inactive': 'var(--color-semantic-light-border-inactive)',
        },
      },
      fontFamily: {
        'primary': 'var(--typography-fontFamily-primary)',
      },
      fontWeight: {
        'regular': 'var(--typography-fontWeight-regular)',
        'medium': 'var(--typography-fontWeight-medium)',
        'semibold': 'var(--typography-fontWeight-semibold)',
        'bold': 'var(--typography-fontWeight-bold)',
      },
      lineHeight: {
        'tight': 'var(--typography-lineHeight-tight)',
        'normal': 'var(--typography-lineHeight-normal)',
        'relaxed': 'var(--typography-lineHeight-relaxed)',
      },
      letterSpacing: {
        'tight': 'var(--typography-letterSpacing-tight)',
        'normal': 'var(--typography-letterSpacing-normal)',
        'small': 'var(--typography-letterSpacing-small)',
        'micro': 'var(--typography-letterSpacing-micro)',
        'none': 'var(--typography-letterSpacing-none)',
      },
      fontSize: {
        '2xs': 'var(--typography-fontSize-2xs)',
        'xs': 'var(--typography-fontSize-xs)',
        's': 'var(--typography-fontSize-s)',
        'm': 'var(--typography-fontSize-m)',
        'l': 'var(--typography-fontSize-l)',
        'xl': 'var(--typography-fontSize-xl)',
        '2xl': 'var(--typography-fontSize-2xl)',
        '3xl': 'var(--typography-fontSize-3xl)',
        '4xl': 'var(--typography-fontSize-4xl)',
        '3xs': 'var(--typography-fontSize-3xs)',
        '4xs': 'var(--typography-fontSize-4xs)',
        '5xs': 'var(--typography-fontSize-5xs)',
      },
      // Typography classes for type styles
      text: {
        'display-large': 'var(--typography-typeStyles-display-large-fontSize)',
        'display-medium': 'var(--typography-typeStyles-display-medium-fontSize)',
        'display-small': 'var(--typography-typeStyles-display-small-fontSize)',
        'heading-extra-large': 'var(--typography-typeStyles-heading-extra-large-fontSize)',
        'heading-large': 'var(--typography-typeStyles-heading-large-fontSize)',
        'heading-medium': 'var(--typography-typeStyles-heading-medium-fontSize)',
        'heading-small': 'var(--typography-typeStyles-heading-small-fontSize)',
        'title-extra-large': 'var(--typography-typeStyles-title-extra-large-fontSize)',
        'title-large': 'var(--typography-typeStyles-title-large-fontSize)',
        'title-medium': 'var(--typography-typeStyles-title-medium-fontWeight)',
        'title-small': 'var(--typography-typeStyles-title-small-fontSize)',
        'title-extra-small': 'var(--typography-typeStyles-title-extra-small-fontSize)',
        'body-extra-large': 'var(--typography-typeStyles-body-extra-large-fontSize)',
        'body-large': 'var(--typography-typeStyles-body-large-fontSize)',
        'body-medium': 'var(--typography-typeStyles-body-medium-fontSize)',
        'body-small': 'var(--typography-typeStyles-body-small-fontSize)',
        'body-extra-small': 'var(--typography-typeStyles-body-extra-small-fontSize)',
        'body-extra-extra-small': 'var(--typography-typeStyles-body-extra-extra-small-fontSize)',
        'label-large': 'var(--typography-typeStyles-label-large-fontSize)',
        'label-medium': 'var(--typography-typeStyles-label-medium-fontSize)',
        'label-small': 'var(--typography-typeStyles-label-small-fontSize)',
        'label-extra-small': 'var(--typography-typeStyles-label-extra-small-fontSize)',
        'label-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-small-fontSize)',
        'label-extra-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-extra-small-fontSize)',
        'label-extra-extra-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-extra-extra-small-fontSize)',
      },
      font: {
        'display-large': 'var(--typography-typeStyles-display-large-fontWeight)',
        'display-medium': 'var(--typography-typeStyles-display-medium-fontWeight)',
        'display-small': 'var(--typography-typeStyles-display-small-fontWeight)',
        'heading-extra-large': 'var(--typography-typeStyles-heading-extra-large-fontWeight)',
        'heading-large': 'var(--typography-typeStyles-heading-large-fontWeight)',
        'heading-medium': 'var(--typography-typeStyles-heading-medium-fontWeight)',
        'heading-small': 'var(--typography-typeStyles-heading-small-fontWeight)',
        'title-extra-large': 'var(--typography-typeStyles-title-extra-large-fontWeight)',
        'title-large': 'var(--typography-typeStyles-title-large-fontWeight)',
        'title-medium': 'var(--typography-typeStyles-title-medium-fontWeight)',
        'title-small': 'var(--typography-typeStyles-title-small-fontWeight)',
        'title-extra-small': 'var(--typography-typeStyles-title-extra-small-fontWeight)',
        'body-extra-large': 'var(--typography-typeStyles-body-extra-large-fontWeight)',
        'body-large': 'var(--typography-typeStyles-body-large-fontWeight)',
        'body-medium': 'var(--typography-typeStyles-body-medium-fontWeight)',
        'body-small': 'var(--typography-typeStyles-body-small-fontWeight)',
        'body-extra-small': 'var(--typography-typeStyles-body-extra-small-fontWeight)',
        'body-extra-extra-small': 'var(--typography-typeStyles-body-extra-extra-small-fontWeight)',
        'label-large': 'var(--typography-typeStyles-label-large-fontWeight)',
        'label-medium': 'var(--typography-typeStyles-label-medium-fontWeight)',
        'label-small': 'var(--typography-typeStyles-label-small-fontWeight)',
        'label-extra-small': 'var(--typography-typeStyles-label-extra-small-fontWeight)',
        'label-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-small-fontWeight)',
        'label-extra-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-extra-small-fontWeight)',
        'label-extra-extra-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-extra-extra-small-fontWeight)',
      },
      leading: {
        'display-large': 'var(--typography-typeStyles-display-large-lineHeight)',
        'display-medium': 'var(--typography-typeStyles-display-medium-lineHeight)',
        'display-small': 'var(--typography-typeStyles-display-small-lineHeight)',
        'heading-extra-large': 'var(--typography-typeStyles-heading-extra-large-lineHeight)',
        'heading-large': 'var(--typography-typeStyles-heading-large-lineHeight)',
        'heading-medium': 'var(--typography-typeStyles-heading-medium-lineHeight)',
        'heading-small': 'var(--typography-typeStyles-heading-small-lineHeight)',
        'title-extra-large': 'var(--typography-typeStyles-title-extra-large-lineHeight)',
        'title-large': 'var(--typography-typeStyles-title-large-lineHeight)',
        'title-medium': 'var(--typography-typeStyles-title-medium-lineHeight)',
        'title-small': 'var(--typography-typeStyles-title-small-lineHeight)',
        'title-extra-small': 'var(--typography-typeStyles-title-extra-small-lineHeight)',
        'body-extra-large': 'var(--typography-typeStyles-body-extra-large-lineHeight)',
        'body-large': 'var(--typography-typeStyles-body-large-letterSpacing)',
        'body-medium': 'var(--typography-typeStyles-body-medium-lineHeight)',
        'body-small': 'var(--typography-typeStyles-body-small-lineHeight)',
        'body-extra-small': 'var(--typography-typeStyles-body-extra-small-lineHeight)',
        'body-extra-extra-small': 'var(--typography-typeStyles-body-extra-extra-small-lineHeight)',
        'label-large': 'var(--typography-typeStyles-label-large-lineHeight)',
        'label-medium': 'var(--typography-typeStyles-label-medium-lineHeight)',
        'label-small': 'var(--typography-typeStyles-label-small-lineHeight)',
        'label-extra-small': 'var(--typography-typeStyles-label-extra-small-lineHeight)',
        'label-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-small-lineHeight)',
        'label-extra-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-extra-small-lineHeight)',
        'label-extra-extra-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-extra-extra-small-lineHeight)',
      },
      tracking: {
        'display-large': 'var(--typography-typeStyles-display-large-letterSpacing)',
        'display-medium': 'var(--typography-typeStyles-display-medium-letterSpacing)',
        'display-small': 'var(--typography-typeStyles-display-small-letterSpacing)',
        'heading-extra-large': 'var(--typography-typeStyles-heading-extra-large-letterSpacing)',
        'heading-large': 'var(--typography-typeStyles-heading-large-letterSpacing)',
        'heading-medium': 'var(--typography-typeStyles-heading-medium-letterSpacing)',
        'heading-small': 'var(--typography-typeStyles-heading-small-letterSpacing)',
        'title-extra-large': 'var(--typography-typeStyles-title-extra-large-letterSpacing)',
        'title-large': 'var(--typography-typeStyles-title-large-letterSpacing)',
        'title-medium': 'var(--typography-typeStyles-title-medium-letterSpacing)',
        'title-small': 'var(--typography-typeStyles-title-small-letterSpacing)',
        'title-extra-small': 'var(--typography-typeStyles-title-extra-small-letterSpacing)',
        'body-extra-large': 'var(--typography-typeStyles-body-extra-large-letterSpacing)',
        'body-large': 'var(--typography-typeStyles-body-large-letterSpacing)',
        'body-medium': 'var(--typography-typeStyles-body-medium-letterSpacing)',
        'body-small': 'var(--typography-typeStyles-body-small-letterSpacing)',
        'body-extra-small': 'var(--typography-typeStyles-body-extra-small-letterSpacing)',
        'body-extra-extra-small': 'var(--typography-typeStyles-body-extra-extra-small-letterSpacing)',
        'label-large': 'var(--typography-typeStyles-label-large-letterSpacing)',
        'label-medium': 'var(--typography-typeStyles-label-medium-letterSpacing)',
        'label-small': 'var(--typography-typeStyles-label-small-letterSpacing)',
        'label-extra-small': 'var(--typography-typeStyles-label-extra-small-letterSpacing)',
        'label-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-small-letterSpacing)',
        'label-extra-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-extra-small-letterSpacing)',
        'label-extra-extra-extra-extra-small': 'var(--typography-typeStyles-label-extra-extra-extra-extra-small-letterSpacing)',
      },
      spacing: {
        'sm': 'var(--spacing-sm)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
        '4xl': 'var(--spacing-4xl)',
        '5xl': 'var(--spacing-5xl)',
        'xxxxl': 'var(--spacing-xxxxl)',
        'xxxl': 'var(--spacing-xxxl)',
        'xxl': 'var(--spacing-xxl)',
        'xl': 'var(--spacing-xl)',
        'l': 'var(--spacing-l)',
        'm': 'var(--spacing-m)',
        'ml': 'var(--spacing-ml)',
        's': 'var(--spacing-s)',
        'xs': 'var(--spacing-xs)',
        'xxs': 'var(--spacing-xxs)',
        'xxxs': 'var(--spacing-xxxs)',
        'xxxxs': 'var(--spacing-xxxxs)',
        'xxxxxs': 'var(--spacing-xxxxxs)',
        'micro-xs': 'var(--spacing-micro-xs)',
        'micro-sm': 'var(--spacing-micro-sm)',
        'micro-md': 'var(--spacing-micro-lg)',
        'micro-lg': 'var(--spacing-micro-lg)',
        'component-xs': 'var(--spacing-component-xs)',
        'component-sm': 'var(--spacing-component-sm)',
        'component-md': 'var(--spacing-component-md)',
        'component-lg': 'var(--spacing-component-xl)',
        'component-xl': 'var(--spacing-component-xl)',
        'button-sm': 'var(--spacing-button-sm)',
        'button-md': 'var(--spacing-button-md)',
        'button-lg': 'var(--spacing-button-lg)',
        'layout-xs': 'var(--spacing-layout-xs)',
        'layout-sm': 'var(--spacing-layout-sm)',
        'layout-md': 'var(--spacing-layout-md)',
        'layout-lg': 'var(--spacing-layout-lg)',
        'layout-xl': 'var(--spacing-layout-xl)',
        'layout-2xl': 'var(--spacing-layout-2xl)',
      },
      borderRadius: {
        'xxs': 'var(--border-radius-xxs)',
        'xs': 'var(--border-radius-xs)',
        's': 'var(--border-radius-s)',
        'm': 'var(--border-radius-m)',
        'l': 'var(--border-radius-l)',
        'none': 'var(--border-radius-none)',
        'full': 'var(--border-radius-full)',
      },
      borderWidth: {
        's': 'var(--border-width-s)',
        'm': 'var(--border-width-m)',
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
}
